"""empty message

Revision ID: d095935f978b
Revises:
Create Date: 2025-08-31 21:10:35.297111

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d095935f978b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index("ix_link_code", "link", ["code"], unique=False)
    op.create_table(
        "detail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.Column("lifetime", sa.Integer(), nullable=True),
        sa.Column("registered", sa.Date(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified", sa.Date(), nullable=True),
        sa.CheckConstraint("length > 0", name="ck_detail_length_positive"),
        sa.CheckConstraint("lifetime IS NULL OR lifetime > 0", name="ck_detail_lifetime_positive"),
        sa.ForeignKeyConstraint(["link_id"], ["link.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id"),
    )
    op.create_index("ix_detail_link_id", "detail", ["link_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detail_link_id", table_name="detail")
    op.drop_table("detail")
    op.drop_index("ix_link_code", table_name="link")
    op.drop_table("link")
    # ### end Alembic commands ###
